postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *postgres
  database: cxwedding_DEV
  username: stockdev
  password: letmein

test:
  <<: *postgres
  database: cxwedding_TEST
  username: stockdev
  password: letmein

production:
  <<: *postgres
  database: db/production.pg
