postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *postgres
  database: cxwedding_DEV
  username: stockdev
  password: letmein

test:
  <<: *postgres
  database: cxwedding_TEST
  username: stockdev
  password: letmein

#production:
#  <<: *postgres
#  database: db/production.pg

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>